version: '2'
services:
    jhipsterdemo-app:
        image: jhipsterdemo
        external_links:
            - jhipsterdemo-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    jhipsterdemo-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jhipsterdemo-cassandra
